<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIBAIL56180" ignored="0" name="Test" tests="2" failures="1" timestamp="09 Sep 2017 14:07:48 GMT" time="0.105" errors="0">
  <testcase name="test1" time="0.024" classname="org.RetryExample"/>
  <testcase name="test2" time="0.009" classname="org.RetryExample">
    <failure type="java.lang.AssertionError" message="expected [test3] but found [test2]">
      <![CDATA[java.lang.AssertionError: expected [test3] but found [test2]
	at org.RetryExample.test2(RetryExample.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
